import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SearchBar from "./components/Searchbar/SearchBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="absolute top-0 left-0 w-full h-full">
          <img
            src="background.png"
            alt="backgroundImage"
            className="h-screen w-full object-cover"
          />
          <div className='absolute top-0 left-0 w-full h-screen bg-gradient-to-b from-black/5 to-black'/>
        </div>
        <div className="relative">
          <SearchBar/>
          {children}
        </div>
      </body>
    </html>
  );
}
